version: 2.1

jobs:
  test-windows:
    parameters:
      java-version:
        type: string
      millargs:
        type: string

    resource_class: windows.medium
    machine:
      image: windows-server-2022-gui:current

    steps:
      - checkout
      - run:
          command: $(echo hello | Out-Host; $?) -and $(echo world | Out-Host; $?)
          shell: powershell.exe
      - run:
          command: echo hello && echo world
          shell: bash.exe
      - run:
          command: echo hello & echo world
          shell: cmd.exe

  test:
    parameters:
      java-version:
        type: string
      millargs:
        type: string

    machine:
      image: ubuntu-2004:current
#    docker:
#      - image: cimg/base:current
    resource_class: large

    steps:
    - checkout
    - run:
        name: "Install OpenJDK"
        command: |
          sudo apt-get update && sudo apt-get install openjdk-<< parameters.java-version >>-jdk
          sudo apt-get install clang
          sudo update-alternatives --set java /usr/lib/jvm/java-<< parameters.java-version >>-openjdk-amd64/bin/java
          sudo update-alternatives --set javac /usr/lib/jvm/java-<< parameters.java-version >>-openjdk-amd64/bin/javac
          java -version
    - run:
        name: "Mill Command"
        command: "./mill -ik << parameters.millargs >>"

workflows:
  all-tests:
    jobs:
    - test:
        name: main-etc-java11
        java-version: "11"
        millargs: '"{main,scalalib,testrunner,testkit,bsp}.__.test"'
    - test:
        name: main-etc-java17
        java-version: "17"
        millargs: '"{main,scalalib,testrunner,testkit,bsp}.__.test"'

      # For most tests, run them arbitrarily on Java 8 or Java 17 on Linux, and
      # on the opposite version on Windows below, so we get decent coverage of
      # each test on each Java version and each operating system
    - test:
        name: scalajslib
        java-version: "11"
        millargs: '"scalajslib.__.test"'
    - test:
        name: scalanativelib
        java-version: "11"
        millargs: '"scalanativelib.__.test"'
    - test:
        name: contrib
        java-version: "17"
        millargs: "contrib._.test"

      # Group these tests together to try and balance out the runtimes of each job
      # Just running in `local` mode since they shouldn't depend on the mode
    - test:
        name: example-javalib-scalalib
        java-version: "17"
        millargs: "'example.{javalib,scalalib}.__.local.test'"
    - test:
        name: example-depth-extending
        java-version: "11"
        millargs: "'example.{depth,extending}.__.local.test'"
    - test:
        name: example-thirdparty-java11
        java-version: "11"
        millargs: "'example.thirdparty[{mockito,acyclic,commons-io}].local.test'"
    - test:
        name: example-thirdparty-java17
        java-version: "17"
        millargs: "'example.thirdparty[{fansi,jimfs,netty,gatling}].local.test'"

      # Most of these integration tests should not depend on which mode they
      # are run in, so just run them in `local`
    - test:
        name: integration
        java-version: "11"
        millargs: "'integration.{failure,feature,ide}[_].local.test'"

      # These invalidation tests need to be exercised in all three execution modes
      # to make sure they work with and without -i/--no-server being passed
    - test:
        name: integration-invalidation-local
        java-version: "17"
        millargs: "'integration.invalidation[_].local.test'"
    - test:
        name: integration-invalidation-fork
        java-version: "17"
        millargs: "'integration.invalidation[_].fork.test'"
    - test:
        name: integration-invalidation-server
        java-version: "17"
        millargs: "'integration.invalidation[_].server.test'"

      # Check docsite compiles
    - test:
        name: docs
        java-version: "17"
        millargs: docs.githubPages


      # just run a subset of examples/ on Windows, because for some reason running
      # the whole suite can take hours on windows v.s. half an hour on linux
    - test-windows:
        name: windows-main-etc
        java-version: 11
        millargs: '"{main,scalalib,bsp}.__.test"'
    - test-windows:
        name: windows-scalajslib
        java-version: 17
        millargs: '"scalajslib.__.test"'
    - test-windows:
        name: windows-example-scalalib-basic
        java-version: 11
        millargs: '"example.scalalib.basic.__.fork.test"'
    - test-windows:
        name: windows-integration-feature
        java-version: 17
        millargs: "'integration.feature[_].fork.test'"
    - test-windows:
        name: windows-integration-invalidation
        java-version: 11
        millargs: "'integration.invalidation[_].server.test'"
    - test-windows:
        name: windows-integration-failure
        java-version: 17
        millargs: "'integration.failure[_].fork.test'"
    - test-windows:
        name: windows-contrib
        java-version: 11
        millargs: "contrib.__.test"